batch_size: 32
epochs: 100
optimizer:
  name: "sgd"
  lr: 1.e-2
  momentum: 0.9
model:
  model_name: "dino_vitb"
  backbone: "deit_base_patch16_224"
  patch_size: 16
  output_size: 304
  checkpoint: "/projects/ag-bozek/kouan/cnf_ssl/data/model_checkpoints/fb_dino/dino_vitbase16_pretrain_full_checkpoint/checkpoint.pth"
  drop_path_rate: 0.0
